apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis.conf: |
{{- if .Values.redisConfig -}}
{{- range $key, $val := .Values.redisConfig -}}
    {{ $key | nindent 4 }} {{ $val }}
{{- end -}}
{{- end -}}
{{- if .Values.redisRenameCommand -}}
{{- range $key, $val := .Values.redisRenameCommand }}
    rename-command {{ $key }} {{ $val | quote }}
{{- end -}}
{{- end -}}
