---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xbrowsersync.fullname" . }}
data:
  settings.json: |
    {
      "db": {
        "host": "{{ .Values.xBrowserSync.dbHost }}"
      },
      "maxSyncSize": {{ .Values.xBrowserSync.maxSyncSize }}
    }
