{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xbrowsersync.fullname" . }}
  labels:
    {{- include "xbrowsersync.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.xBrowserSync.username }}
  username: {{ .Values.xBrowserSync.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.xBrowserSync.password }}
  password: {{ .Values.xBrowserSync.password | b64enc | quote }}
  {{- end }}
{{- end }}
