{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hellofresh.fullname" . }}
  labels:
    {{- include "hellofresh.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.username }}
  username: {{ .Values.secrets.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.password }}
  password: {{ .Values.secrets.password | b64enc | quote }}
  {{- end }}
{{- end }}
