{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
{{- if not .Values.serviceAccount.automount }}
automountServiceAccountToken: false
{{- end }}
metadata:
  name: {{ include "whoami.serviceAccountName" . }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
